version: '3.1'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    shm_size: 4gb
    ports:
      - "8888:8888"
      - "6006:6006"
